### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by tochman**
I'm not sure what happened but am I duplicating commits in this one? 

Ready for review!
@diraulo

### CODE REVIEW

**Review by diraulo — APPROVED** [review]

**Review by diraulo — CHANGES_REQUESTED** [review]
Actually.. There's an ambiguous step definition somewhere...

**Comment by diraulo** [comment]
@tochman 
```shell
Ambiguous match of "I click on dropdown menu "Admin"":

features/step_definitions/steps.rb:199:in `/^I click on dropdown menu "([^"]*)"$/'
features/step_definitions/steps.rb:237:in `/^I click on dropdown menu "([^"]*)"$/'
```

**Comment by tochman** [comment]
Right, will fix

**Comment by tochman** [comment]
There ware some step defs duplicated. Sloppy of me. Sorry ;-)

**Comment by tochman** [comment]
These'r nothing here worth merging. Closing this.

**Pull request closed without merging**
