### PR TITLE
Pushes some code from develop to staging

### PR DESCRIPTION
**Pull request by diraulo**
Title of the PT story: **No PT Story**

Description of the PR:

First push from `develop` to `staging` to setup CI

### CODE REVIEW

**Comment by diraulo** [comment]
@tochman Can you merge this one for me please

**Comment by diraulo** [comment]
@tochman we should only squash commits from PRs to `develop` the rest of the chain we do normal merges. 

Otherwise, every time we create PRs from `develop` to `staging` that huge pile of commits will show up in the diff.

**Comment by tochman** [comment]
True. Sorry
What do we do now?

**Comment by diraulo** [comment]
we'll fix it at the next one 😉

**Comment by diraulo** [comment]
@tochman unless you want to revert the merge and redo it.

**Comment by tochman** [comment]
Can you do it @diraulo?

**Pull request merged**
