### PR TITLE
Api

### PR DESCRIPTION
**Pull request by tochman**
PT Story: https://www.pivotaltracker.com/story/show/128270443

- adds namespace to `routes.rb` 
- creates a ApiController
- adds `routes/api` folder for specs
- adds helper method for parsing `response.body` as JSON to simplify tests.

### CODE REVIEW

**Comment by diraulo** [comment]
@tochman weird that [this](https://coveralls.io/jobs/17286751/source_files/1167344721) isn't covered

**Comment by tochman** [comment]
Yeah, what's up with that?

**Comment by tochman** [comment]
How should we deal with this?

**Comment by diraulo** [comment]
@tochman it's the coverage merge that's messed up. It's not merging both results as it should.
When I run cucumber, then Rspec I get different (higher) coverage. When I do Rspec then cucumber, the final result that is submitted to coveralls is the cucumber coverage only and not the merge

**Comment by tochman** [comment]
I see. How do we solve this?

**Comment by diraulo** [comment]
@tochman not that simple. I created an issue for this on PT. Started to look at it this morning and got the merge to work at least, but it's still skipping some controllers... 

We can go ahead and merge this one unless there are other concerns here. We'll take care of coverage report in a separate PR

**Pull request merged**
