### PR TITLE
specify test suites commands for simplecov

### PR DESCRIPTION
**Pull request by diraulo**
Title of the PT story: no story

Description of the PR:

1. Specify test suites commands for `simplecov`. This should allow it to group coverage results appropriately now and hopefully partly fix the coverage issue we've been experiencing...

Ready for review!
@tochman

### CODE REVIEW

**Comment by tochman** [comment]
Should we see test coverage on this PR or once it is merged?

**Comment by diraulo** [comment]
screenshot 2016-11-10 18 17 27

😞

**Comment by tochman** [comment]
Yes... :-(

**Comment by diraulo** [comment]
At one run on my computer I got 98% 🤔

**Comment by tochman** [comment]
Well, if we merge this we'll see. Let's move on. ;-) I have a few hours left of the day and would like to push out another feature.

**Comment by diraulo** [comment]
give me few minutes.

**Comment by tochman** [comment]
Shit... Sorry

**Comment by diraulo** [comment]
It's all good :)

**Pull request merged**
